# Number of days of inactivity before an issue becomes stale
daysUntilStale: 14
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 4
# Issues with these labels will never be considered stale
exemptLabels:
    - ðŸ“Œ pinned
    - ðŸ’¬ discuss
    - ðŸ— enhancement
    - ðŸ“– documentation
    - ðŸ”¨ breaking-change
    - ðŸš§ experimental
    - ðŸ™ help wanted
    - ðŸ‘“ needs investigation
    - âœ‹ on hold

# Label to use when marking an issue as stale
staleLabel: ðŸš¶ stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
# Limit to only `issues` or `pulls`
only: issues
# Comment to post when removing the stale label.
unmarkComment: >
    This issue has been automatically unmarked as stale. Please disregard previous warnings.
