name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Build check
        run: npm run build:check

      - name: Build packages
        run: npm run build:test

      - name: Test
        run: npm test -- -i

      - name: Check size
        run: npm -w mobx run check-size

      - name: Test performance
        run: npm -w mobx run test:performance
